export type BreedInfo = {
  name: string;
  species: 'Cachorro' | 'Gato' | 'Pássaro' | 'Coelho' | 'Hamster' | 'Peixe' | 'Réptil' | 'Cobaia' | 'Chinchila' | 'Furão';
  origin: string;
  size: 'Pequeno' | 'Médio' | 'Grande' | 'Gigante';
  lifespan: string; // ex: "12-15 anos"
  temperament: string[];
  characteristics: string;
  care: string[];
  curiosity: string;
  emoji: string;
};

const BREEDS: BreedInfo[] = [
  // ── Cachorros ──────────────────────────────────────────────────────────────
  {
    name: 'Labrador Retriever',
    species: 'Cachorro',
    origin: 'Canadá',
    size: 'Grande',
    lifespan: '10–12 anos',
    temperament: ['Amigável', 'Brincalhão', 'Leal', 'Gentil'],
    characteristics: 'Pelagem curta densa, corpo musculoso. Ótimo nadador com cauda em forma de lontra.',
    care: ['Escovação semanal', 'Exercício diário intenso', 'Controle do peso — propenso à obesidade', 'Limpeza regular das orelhas'],
    curiosity: 'É uma das raças mais populares do mundo há mais de 30 anos consecutivos.',
    emoji: '🐕',
  },
  {
    name: 'Golden Retriever',
    species: 'Cachorro',
    origin: 'Escócia',
    size: 'Grande',
    lifespan: '10–12 anos',
    temperament: ['Dócil', 'Confiável', 'Amigável', 'Paciente'],
    characteristics: 'Pelagem dourada densa e ondulada. Expressão gentil e olhos escuros.',
    care: ['Escovação 2x por semana', 'Exercício diário', 'Banhos regulares', 'Verificação das orelhas semanalmente'],
    curiosity: 'Originalmente criado para buscar aves caçadas sem danificá-las — daí o "retriever".',
    emoji: '🐕',
  },
  {
    name: 'Poodle',
    species: 'Cachorro',
    origin: 'França / Alemanha',
    size: 'Médio',
    lifespan: '12–15 anos',
    temperament: ['Inteligente', 'Ativo', 'Sociável', 'Fiel'],
    characteristics: 'Pelagem encaracolada e densa, hipoalergênica. Vem em quatro tamanhos: padrão, médio, miniatura e toy.',
    care: ['Tosa a cada 6–8 semanas', 'Escovação frequente', 'Exercício diário moderado', 'Estimulação mental diária'],
    curiosity: 'Apesar da fama francesa, a raça tem origem alemã — era usada para buscar patos na água.',
    emoji: '🐩',
  },
  {
    name: 'Bulldog Francês',
    species: 'Cachorro',
    origin: 'França',
    size: 'Pequeno',
    lifespan: '10–12 anos',
    temperament: ['Adaptável', 'Brincalhão', 'Sociável', 'Tranquilo'],
    characteristics: 'Orelhas de morcego, focinho achatado, corpo compacto e musculoso.',
    care: ['Limpeza das pregas da pele', 'Evitar calor excessivo', 'Exercícios leves', 'Monitorar respiração'],
    curiosity: 'É uma das raças mais populares em apartamentos por ser calma e não latir muito.',
    emoji: '🐾',
  },
  {
    name: 'Yorkshire Terrier',
    species: 'Cachorro',
    origin: 'Inglaterra',
    size: 'Pequeno',
    lifespan: '13–16 anos',
    temperament: ['Corajoso', 'Afetivo', 'Espirituoso', 'Curioso'],
    characteristics: 'Pelagem longa, sedosa e azul-aço com dourado. Pequeno mas com personalidade grande.',
    care: ['Escovação diária', 'Tosa regular', 'Higiene dental rigorosa', 'Passeios curtos diários'],
    curiosity: 'Criado originalmente para caçar ratos em fábricas têxteis na Inglaterra do século XIX.',
    emoji: '🐕',
  },
  {
    name: 'Shih Tzu',
    species: 'Cachorro',
    origin: 'China / Tibet',
    size: 'Pequeno',
    lifespan: '10–16 anos',
    temperament: ['Afetuoso', 'Brincalhão', 'Sociável', 'Resiliente'],
    characteristics: 'Pelagem longa e fluida, face achatada, olhos grandes e redondos.',
    care: ['Escovação diária', 'Tosa mensal', 'Limpeza dos olhos diária', 'Banho semanal'],
    curiosity: 'Nome significa "cão leão" em mandarim — era cão de colo dos imperadores chineses.',
    emoji: '🐕',
  },
  {
    name: 'Beagle',
    species: 'Cachorro',
    origin: 'Inglaterra',
    size: 'Médio',
    lifespan: '12–15 anos',
    temperament: ['Curioso', 'Amigável', 'Alegre', 'Determinado'],
    characteristics: 'Orelhas longas e caídas, olhar expressivo, pelo curto tricolor (preto, marrom e branco).',
    care: ['Exercício diário vigoroso', 'Monitorar dieta — propenso a obesidade', 'Limpeza das orelhas', 'Cerca segura — grande instinto de fuga'],
    curiosity: 'O Beagle é a raça usada em aeroportos para farejar contrabando por seu olfato excepcional.',
    emoji: '🐕',
  },
  {
    name: 'Dachshund',
    species: 'Cachorro',
    origin: 'Alemanha',
    size: 'Pequeno',
    lifespan: '12–16 anos',
    temperament: ['Curioso', 'Espirituoso', 'Devotado', 'Bravo'],
    characteristics: 'Corpo alongado, pernas curtas. Disponível em pelo liso, longo ou crespo.',
    care: ['Evitar escadas e saltos — colunas frágeis', 'Controle de peso rigoroso', 'Exercício moderado', 'Higiene dental'],
    curiosity: 'Chamado de "salsichinha" no Brasil, foi criado para caçar texugos em tocas estreitas.',
    emoji: '🌭',
  },
  {
    name: 'Pug',
    species: 'Cachorro',
    origin: 'China',
    size: 'Pequeno',
    lifespan: '12–15 anos',
    temperament: ['Sociável', 'Afetuoso', 'Brincalhão', 'Charming'],
    characteristics: 'Focinho achatado, muitas pregas, olhos grandes e salientes, corpo robusto e compacto.',
    care: ['Limpeza das pregas faciais', 'Evitar calor e umidade', 'Exercícios leves', 'Monitorar respiração'],
    curiosity: 'O lema oficial da raça é "multum in parvo" — muito em pouco — por ser grande em personalidade.',
    emoji: '🐾',
  },
  {
    name: 'Maltês',
    species: 'Cachorro',
    origin: 'Malta',
    size: 'Pequeno',
    lifespan: '12–15 anos',
    temperament: ['Gentil', 'Afetivo', 'Brincalhão', 'Responsivo'],
    characteristics: 'Pelagem branca, longa e sedosa. Sem subpelo — hipoalergênico.',
    care: ['Escovação diária', 'Banho semanal', 'Limpeza dos olhos', 'Tosa regular'],
    curiosity: 'Uma das raças mais antigas do mundo — existem registros de 3.500 anos.',
    emoji: '🤍',
  },
  {
    name: 'Boxer',
    species: 'Cachorro',
    origin: 'Alemanha',
    size: 'Grande',
    lifespan: '10–12 anos',
    temperament: ['Brincalhão', 'Energético', 'Leal', 'Protetor'],
    characteristics: 'Corpo musculoso, focinho quadrado, orelhas caídas. Expressão séria mas temperamento alegre.',
    care: ['Exercício diário intenso', 'Estimulação mental', 'Limpeza das pregas do focinho', 'Vacinação em dia'],
    curiosity: 'Apesar do nome e aparência intimidadora, é conhecido como o "eterno filhote" pelo temperamento jovial.',
    emoji: '🐕',
  },
  {
    name: 'Rottweiler',
    species: 'Cachorro',
    origin: 'Alemanha',
    size: 'Grande',
    lifespan: '8–10 anos',
    temperament: ['Confiante', 'Protetor', 'Corajoso', 'Leal'],
    characteristics: 'Corpo massivo e musculoso, pelagem preta com marcas ferrugem. Porte imponente.',
    care: ['Socialização desde filhote', 'Treinamento consistente', 'Exercício diário', 'Escovação semanal'],
    curiosity: 'Foi um dos primeiros cães de serviço usados pela polícia alemã no século XX.',
    emoji: '🐕',
  },
  {
    name: 'Pastor Alemão',
    species: 'Cachorro',
    origin: 'Alemanha',
    size: 'Grande',
    lifespan: '9–13 anos',
    temperament: ['Inteligente', 'Confiante', 'Corajoso', 'Versátil'],
    characteristics: 'Corpo atlético, pelagem dupla densa, orelinhas eretas, cauda baixa e peluda.',
    care: ['Exercício intenso diário', 'Escovação frequente', 'Estimulação mental', 'Socialização ampla'],
    curiosity: 'É a segunda raça mais inteligente do mundo segundo o psicólogo Stanley Coren.',
    emoji: '🐕',
  },
  {
    name: 'Border Collie',
    species: 'Cachorro',
    origin: 'Reino Unido',
    size: 'Médio',
    lifespan: '12–15 anos',
    temperament: ['Inteligente', 'Energético', 'Responsivo', 'Tenaz'],
    characteristics: 'Pelagem de comprimento médio, olhos de cores diferentes são comuns. Postura de pastoreio característica.',
    care: ['Exercício muito intenso diário', 'Estimulação mental constante', 'Treinamento regular', 'Escovação semanal'],
    curiosity: 'Considerado o cão mais inteligente do mundo — capaz de aprender mais de 1.000 palavras.',
    emoji: '🐕',
  },
  {
    name: 'Husky Siberiano',
    species: 'Cachorro',
    origin: 'Sibéria, Rússia',
    size: 'Médio',
    lifespan: '12–14 anos',
    temperament: ['Agitado', 'Amigável', 'Gentil', 'Alertas'],
    characteristics: 'Olhos azuis ou heterocromia, pelagem densa e dupla, orelhas eretas. Aparência de lobo.',
    care: ['Exercício intenso diário', 'Escovação 2x por semana (diária na muda)', 'Ambiente fresco', 'Cercas altas — grande instinto de fuga'],
    curiosity: 'Foi criado pelo povo Chukchi na Sibéria para puxar trenós por longas distâncias em temperaturas extremas.',
    emoji: '🐺',
  },
  {
    name: 'Spitz Alemão',
    species: 'Cachorro',
    origin: 'Alemanha',
    size: 'Pequeno',
    lifespan: '13–15 anos',
    temperament: ['Vivaz', 'Inteligente', 'Curioso', 'Dedicado'],
    characteristics: 'Pelagem densa e espessa, focinho pontudo, orelhas eretas, cauda enrolada sobre o dorso.',
    care: ['Escovação 2x por semana', 'Estimulação mental', 'Exercício moderado', 'Socialização precoce'],
    curiosity: 'O Lulu da Pomerânia é um Spitz miniatura — ficou famoso por ser o cão favorito da Rainha Vitória.',
    emoji: '🦊',
  },
  {
    name: 'Chihuahua',
    species: 'Cachorro',
    origin: 'México',
    size: 'Pequeno',
    lifespan: '12–20 anos',
    temperament: ['Corajoso', 'Expressivo', 'Ágil', 'Devoto'],
    characteristics: 'O menor cão do mundo. Cabeça em forma de maçã, olhos grandes e salientes.',
    care: ['Proteção do frio', 'Higiene dental rigorosa', 'Exercício leve diário', 'Socialização precoce'],
    curiosity: 'É a raça com maior longevidade — muitos vivem além de 15 anos.',
    emoji: '🐕',
  },
  {
    name: 'Lhasa Apso',
    species: 'Cachorro',
    origin: 'Tibet',
    size: 'Pequeno',
    lifespan: '12–15 anos',
    temperament: ['Assertivo', 'Brincalhão', 'Responsivo', 'Reservado'],
    characteristics: 'Pelagem longa até o chão, franjas sobre os olhos, cauda enrolada.',
    care: ['Escovação diária', 'Tosa regular', 'Limpeza dos olhos', 'Banhos quinzenais'],
    curiosity: 'Cão sagrado no Tibet — era dado como presente de boa sorte. Nunca vendido, apenas presenteado.',
    emoji: '🐕',
  },
  // ── Gatos ──────────────────────────────────────────────────────────────────
  {
    name: 'Persa',
    species: 'Gato',
    origin: 'Irã (antiga Pérsia)',
    size: 'Médio',
    lifespan: '10–17 anos',
    temperament: ['Calmo', 'Afetuoso', 'Dócil', 'Reservado'],
    characteristics: 'Pelos longos e densíssimos, face achatada, nariz pequeno, olhos grandes e redondos.',
    care: ['Escovação diária obrigatória', 'Limpeza dos olhos diária', 'Banho mensal', 'Ambiente tranquilo'],
    curiosity: 'O Persa foi introduzido na Europa no século XVII pelo explorador italiano Pietro della Valle.',
    emoji: '🐱',
  },
  {
    name: 'Maine Coon',
    species: 'Gato',
    origin: 'EUA (Maine)',
    size: 'Grande',
    lifespan: '12–15 anos',
    temperament: ['Sociável', 'Brincalhão', 'Gentil', 'Inteligente'],
    characteristics: 'Um dos maiores gatos domésticos. Pelos semiflongos, tufos nas orelhas, cauda peluda.',
    care: ['Escovação 2x por semana', 'Brinquedos e enriquecimento ambiental', 'Exercício regular', 'Monitorar articulações'],
    curiosity: 'Apesar das lendas, não tem nenhum parentesco com guaxinins — são apenas parecidos.',
    emoji: '🐱',
  },
  {
    name: 'Siamês',
    species: 'Gato',
    origin: 'Tailândia',
    size: 'Médio',
    lifespan: '12–20 anos',
    temperament: ['Vocal', 'Sociável', 'Curioso', 'Inteligente'],
    characteristics: 'Corpo elegante e esguio, olhos azuis intensos, pontas escuras (máscara, orelhas, patas e cauda).',
    care: ['Companhia frequente — detesta solidão', 'Estimulação mental', 'Escovação semanal', 'Brinquedos interativos'],
    curiosity: 'É um dos gatos mais "falantes" do mundo — capaz de imitar o choro de bebês humanos.',
    emoji: '🐱',
  },
  {
    name: 'Ragdoll',
    species: 'Gato',
    origin: 'EUA (Califórnia)',
    size: 'Grande',
    lifespan: '12–17 anos',
    temperament: ['Dócil', 'Calmo', 'Afetuoso', 'Gentil'],
    characteristics: 'Corpo grande e musculoso, pelos semilongos, olhos azuis brilhantes. Ficam flácidos no colo.',
    care: ['Escovação 2x por semana', 'Brinquedos leves', 'Monitorar coração — propenso a cardiomiopatia', 'Ambiente interno'],
    curiosity: 'O nome vem de sua característica única: ficam completamente relaxados (como um boneco de trapo) quando pegos no colo.',
    emoji: '🐱',
  },
  {
    name: 'British Shorthair',
    species: 'Gato',
    origin: 'Reino Unido',
    size: 'Grande',
    lifespan: '12–20 anos',
    temperament: ['Calmo', 'Independente', 'Afetuoso', 'Tranquilo'],
    characteristics: 'Corpo robusto e arredondado, pelagem densa e dura, bochechas pronunciadas.',
    care: ['Escovação semanal', 'Monitorar peso — propenso à obesidade', 'Exercício moderado', 'Brinquedos de estimulação'],
    curiosity: 'O famoso Gato de Cheshire de Alice no País das Maravilhas foi baseado no British Shorthair.',
    emoji: '🐱',
  },
  {
    name: 'Bengal',
    species: 'Gato',
    origin: 'EUA',
    size: 'Médio',
    lifespan: '12–16 anos',
    temperament: ['Ativo', 'Curioso', 'Inteligente', 'Energético'],
    characteristics: 'Pelagem com manchas ou rosetas como leopardo, corpo atlético, personalidade selvagem.',
    care: ['Exercício intenso e brinquedos diários', 'Enriquecimento ambiental abundante', 'Escovação semanal', 'Água fresca sempre disponível — adoram água'],
    curiosity: 'É um híbrido entre gato doméstico e gato-leopardo asiático (Prionailurus bengalensis).',
    emoji: '🐆',
  },
  {
    name: 'Sphynx',
    species: 'Gato',
    origin: 'Canadá',
    size: 'Médio',
    lifespan: '8–14 anos',
    temperament: ['Extrovertido', 'Carinhoso', 'Espirituoso', 'Sociável'],
    characteristics: 'Sem pelos (ou com penugem fina), pele enrugada, orelhas grandes, aparência alien.',
    care: ['Banho semanal — pele oleosa', 'Proteção do frio', 'Limpeza das orelhas semanal', 'Monitorar coração'],
    curiosity: 'Apesar de parecer nu, não é hipoalergênico — a alergia é à proteína Fel d1 na saliva, não no pelo.',
    emoji: '🐱',
  },
  {
    name: 'Scottish Fold',
    species: 'Gato',
    origin: 'Escócia',
    size: 'Médio',
    lifespan: '11–14 anos',
    temperament: ['Dócil', 'Afetuoso', 'Brincalhão', 'Adaptável'],
    characteristics: 'Orelhas dobradas para frente, olhos redondos grandes, expressão de coruja. Corpo arredondado.',
    care: ['Monitorar articulações — propenso à osteocondrodisplasia', 'Escovação semanal', 'Brinquedos interativos', 'Veterinário regular'],
    curiosity: 'Toda linhagem de Scottish Fold descende de uma gata chamada Susie, encontrada em uma fazenda escocesa em 1961.',
    emoji: '🐱',
  },
  // ── Pássaros ────────────────────────────────────────────────────────────────
  { name: 'Calopsita', species: 'Pássaro', origin: 'Austrália', size: 'Pequeno', lifespan: '15–20 anos', temperament: ['Dócil', 'Carinhoso', 'Curioso'], characteristics: 'Penacho característico, bochecha laranja, sociável e fácil de treinar.', care: ['Gaiola espaçosa', 'Socialização diária', 'Dieta variada'], curiosity: 'São os pássaros de estimação mais populares do mundo depois do periquito.', emoji: '🦜' },
  { name: 'Periquito', species: 'Pássaro', origin: 'Austrália', size: 'Pequeno', lifespan: '5–10 anos', temperament: ['Ativo', 'Sociável', 'Brincalhão'], characteristics: 'Pequeno, colorido, fácil adaptação. Vem em diversas cores.', care: ['Par para companhia', 'Brinquedos variados', 'Fora da gaiola diariamente'], curiosity: 'Podem aprender centenas de palavras se treinados desde cedo.', emoji: '🦜' },
  { name: 'Agapornis', species: 'Pássaro', origin: 'África', size: 'Pequeno', lifespan: '10–15 anos', temperament: ['Afetuoso', 'Territorial', 'Brincalhão'], characteristics: 'Conhecido como "pássaro do amor" — vive aos pares. Colorido e compacto.', care: ['Manter em par', 'Gaiola ampla', 'Enriquecimento ambiental'], curiosity: 'O nome vem do grego "agape" (amor) + "ornis" (pássaro).', emoji: '🦜' },
  { name: 'Canário', species: 'Pássaro', origin: 'Ilhas Canárias', size: 'Pequeno', lifespan: '10–15 anos', temperament: ['Tranquilo', 'Independente', 'Musical'], characteristics: 'Famoso pelo canto melodioso. Amarelo clássico ou em outras cores.', care: ['Gaiola vertical para voo', 'Silêncio e rotina', 'Alimentação à base de sementes e frutas'], curiosity: 'Os machos cantam mais que as fêmeas, especialmente na época de reprodução.', emoji: '🐦' },
  { name: 'Papagaio', species: 'Pássaro', origin: 'América do Sul', size: 'Médio', lifespan: '40–60 anos', temperament: ['Inteligente', 'Vocal', 'Sociável'], characteristics: 'Grande capacidade de imitar sons e falar. Plumagem verde característica.', care: ['Interação diária por horas', 'Dieta rica e variada', 'Brinquedos desafiadores', 'Veterinário aviário anual'], curiosity: 'Podem viver mais que seu tutor — é comum fazer testamento para papagaios.', emoji: '🦜' },
  { name: 'Cacatua', species: 'Pássaro', origin: 'Austrália / Oceania', size: 'Médio', lifespan: '40–70 anos', temperament: ['Afetuoso', 'Barulhento', 'Sociável'], characteristics: 'Penacho erétil característico, branca ou rosacea. Extremamente apegada ao tutor.', care: ['Horas de interação diária', 'Brinquedos para destruir', 'Dieta peletizada'], curiosity: 'São considerados os pássaros mais "abraçáveis" — sofrem muito de solidão.', emoji: '🦜' },
  // ── Coelhos ─────────────────────────────────────────────────────────────────
  { name: 'Mini Coelho', species: 'Coelho', origin: 'Europa', size: 'Pequeno', lifespan: '8–12 anos', temperament: ['Dócil', 'Curioso', 'Tímido'], characteristics: 'Porte reduzido, orelhas eretas, muito popular como pet doméstico.', care: ['Feno à vontade', 'Espaço para correr', 'Higiene do espaço diária'], curiosity: 'Coelhos são mais limpos que cachorros e podem aprender a usar caixa de areia.', emoji: '🐰' },
  { name: 'Angorá', species: 'Coelho', origin: 'Turquia', size: 'Médio', lifespan: '7–12 anos', temperament: ['Calmo', 'Dócil', 'Tranquilo'], characteristics: 'Pelo extremamente longo e macio. Aparência de bola de pelúcia.', care: ['Escovação diária obrigatória', 'Tosa trimestral', 'Feno de qualidade'], curiosity: 'Seus pelos são usados para produzir lã de angorá — mais macia que a de ovelha.', emoji: '🐰' },
  { name: 'Holland Lop', species: 'Coelho', origin: 'Holanda', size: 'Pequeno', lifespan: '7–14 anos', temperament: ['Brincalhão', 'Sociável', 'Afetuoso'], characteristics: 'Orelhas caídas ao lado da cabeça. Rosto achatado, corpo compacto e robusto.', care: ['Interação diária', 'Feno ilimitado', 'Espaço para explorar'], curiosity: 'É uma das raças de coelho mais populares nos EUA, criada nos anos 1950.', emoji: '🐰' },
  { name: 'Rex', species: 'Coelho', origin: 'França', size: 'Grande', lifespan: '5–6 anos', temperament: ['Calmo', 'Dócil', 'Materno'], characteristics: 'Pelo curto aveludado e denso, sem pelos de guarda longos. Textura única.', care: ['Espaço amplo', 'Socialização com outros coelhos', 'Dieta equilibrada'], curiosity: 'Sua pelagem mutante foi descoberta em 1919 em uma ninhada de coelhos selvagens na França.', emoji: '🐰' },
  // ── Hamsters ─────────────────────────────────────────────────────────────────
  { name: 'Sírio (Dourado)', species: 'Hamster', origin: 'Síria', size: 'Pequeno', lifespan: '2–3 anos', temperament: ['Independente', 'Ativo à noite', 'Solitário'], characteristics: 'O maior dos hamsters domésticos. Pode ter pelagem curta, longa ou satin.', care: ['Gaiola individual', 'Roda de exercício obrigatória', 'Substrato profundo para cavar'], curiosity: 'Na natureza, escava túneis de até 1 metro de profundidade para estocar alimentos.', emoji: '🐹' },
  { name: 'Anão Russo (Djungarian)', species: 'Hamster', origin: 'Rússia / Ásia Central', size: 'Pequeno', lifespan: '1,5–3 anos', temperament: ['Tímido', 'Curioso', 'Rápido'], characteristics: 'Menor que o sírio. Linha dorsal escura característica. Pode mudar de cor no inverno.', care: ['Gaiola com barras estreitas', 'Roda pequena', 'Manipulação cuidadosa — muito rápido'], curiosity: 'Na Sibéria, consegue correr até 20 km por noite em busca de alimento.', emoji: '🐹' },
  { name: 'Roborovski', species: 'Hamster', origin: 'China / Mongólia', size: 'Pequeno', lifespan: '3–3,5 anos', temperament: ['Ativo', 'Curioso', 'Tímido'], characteristics: 'O menor hamster doméstico (4–5 cm). Sem linha dorsal. Extremamente rápido.', care: ['Observação mais que manipulação', 'Roda de corrida', 'Gaiola bem vedada'], curiosity: 'É o hamster com maior longevidade proporcional — vive até 3,5 anos.', emoji: '🐹' },
  { name: 'Chinchila (hamster)', species: 'Hamster', origin: 'Europa', size: 'Pequeno', lifespan: '2–3 anos', temperament: ['Dócil', 'Sociável', 'Curioso'], characteristics: 'Pelagem cinza-azulada densa, semelhante à chinchila real. Corpo arredondado.', care: ['Substrato macio', 'Brinquedos variados', 'Manusear gentilmente'], curiosity: 'Não tem parentesco com a chinchila real — o nome é por causa da semelhança da pelagem.', emoji: '🐹' },
  // ── Peixes ───────────────────────────────────────────────────────────────────
  { name: 'Betta', species: 'Peixe', origin: 'Tailândia', size: 'Pequeno', lifespan: '2–4 anos', temperament: ['Territorial', 'Agressivo com machos', 'Curioso'], characteristics: 'Nadadeiras longas e coloridas. Respira ar atmosférico — não precisa de aerador.', care: ['Aquário individual para machos', 'Água aquecida (24–28°C)', 'Filtro suave'], curiosity: 'Na Tailândia, são usados em competições de luta — apostas regulamentadas pelo governo.', emoji: '🐟' },
  { name: 'Goldfish (Peixinho Dourado)', species: 'Peixe', origin: 'China', size: 'Médio', lifespan: '10–15 anos', temperament: ['Pacífico', 'Social', 'Ativo'], characteristics: 'Diversas variedades (comum, veiltail, oranda). Produz muito dejeto.', care: ['Aquário grande (min. 40L por peixe)', 'Filtro potente', 'Troca parcial de água semanal'], curiosity: 'Podem viver mais de 20 anos se bem cuidados — o recorde é de 43 anos.', emoji: '🐟' },
  { name: 'Tetra Neon', species: 'Peixe', origin: 'América do Sul', size: 'Pequeno', lifespan: '5–10 anos', temperament: ['Pacífico', 'Cardume', 'Tímido'], characteristics: 'Linha azul e vermelha fluorescente. Vive em cardumes de no mínimo 6 indivíduos.', care: ['Água ácida e mole', 'Plantas aquáticas', 'Cardume mínimo de 6', 'Iluminação moderada'], curiosity: 'Seu brilho fluorescente é produzido por células chamadas cromatóforos, não por pigmento.', emoji: '🐠' },
  { name: 'Acará Disco', species: 'Peixe', origin: 'Amazônia', size: 'Médio', lifespan: '10–15 anos', temperament: ['Sensível', 'Social', 'Tímido'], characteristics: 'Formato redondo achatado, coloração vibrante. Considerado o "rei do aquário".', care: ['Água quente (28–32°C)', 'Troca de água frequente', 'Aquário grande (min. 200L)', 'Alimentação viva ou congelada'], curiosity: 'É considerado o peixe de aquário mais exigente — requer cuidados de nível avançado.', emoji: '🐠' },
  { name: 'Platy', species: 'Peixe', origin: 'América Central', size: 'Pequeno', lifespan: '3–5 anos', temperament: ['Pacífico', 'Ativo', 'Social'], characteristics: 'Resistente, colorido, ideal para iniciantes. Fácil reprodução.', care: ['Aquário de 40L+', 'Filtro básico', 'Temperatura 20–25°C', 'Companhia de outros platys'], curiosity: 'É um dos peixes mais indicados para quem está começando no aquarismo.', emoji: '🐟' },
  // ── Répteis ──────────────────────────────────────────────────────────────────
  { name: 'Dragão Barbudo (Bearded Dragon)', species: 'Réptil', origin: 'Austrália', size: 'Médio', lifespan: '10–15 anos', temperament: ['Dócil', 'Curioso', 'Calmo'], characteristics: 'Escamas em volta da garganta que se inflam. Extremamente dócil com humanos.', care: ['Terrário grande com UV-B', 'Temperatura 35–42°C na área de basking', 'Dieta variada (insetos + vegetais)', 'Banhos semanais'], curiosity: 'É o réptil doméstico mais popular do mundo — considerado o "cachorro dos répteis".', emoji: '🦎' },
  { name: 'Leopard Gecko', species: 'Réptil', origin: 'Paquistão / Afeganistão', size: 'Pequeno', lifespan: '15–20 anos', temperament: ['Dócil', 'Noturno', 'Tranquilo'], characteristics: 'Manchas como leopardo, cauda grossa (reserva de gordura), olhos com pupila vertical.', care: ['Terrário com esconderijos', 'Temperatura 25–32°C', 'Dieta de insetos vivos', 'Caixa de muda úmida'], curiosity: 'Diferente de outras espécies, tem pálpebras — pode piscar, o que é raro em lagartos.', emoji: '🦎' },
  { name: 'Iguana Verde', species: 'Réptil', origin: 'América Central e do Sul', size: 'Grande', lifespan: '10–15 anos', temperament: ['Territorial', 'Calmo quando adulto', 'Curioso'], characteristics: 'Grande lagarto verde com crista dorsal. Pode atingir 1,5–2m.', care: ['Terrário enorme ou quarto dedicado', 'UV-B obrigatório', 'Dieta 100% vegetal', 'Banhos frequentes'], curiosity: 'Iguanas podem soltar a cauda como defesa — ela regenera parcialmente.', emoji: '🦎' },
  { name: 'Tartaruga-de-orelha-vermelha', species: 'Réptil', origin: 'América do Norte', size: 'Médio', lifespan: '20–40 anos', temperament: ['Ativo', 'Territorial', 'Curioso'], characteristics: 'Marca vermelha atrás dos olhos, semi-aquática. A mais popular como pet.', care: ['Aquaterrário', 'Filtro potente', 'Área de basking com UV-B', 'Alimentação variada'], curiosity: 'Podem viver mais de 40 anos — muitos acabam abandonados quando crescem demais.', emoji: '🐢' },
  { name: 'Corn Snake (Cobra do Milho)', species: 'Réptil', origin: 'América do Norte', size: 'Médio', lifespan: '15–20 anos', temperament: ['Dócil', 'Calmo', 'Curioso'], characteristics: 'Cobra não-peçonhenta, padrão xadrez colorido. Ideal para iniciantes com répteis.', care: ['Terrário com tampa segura', 'Temperatura 24–30°C', 'Esconderijos', 'Roedores congelados/descongelados'], curiosity: 'É recomendada para quem quer começar com cobras — praticamente nunca morde.', emoji: '🐍' },

  // ── Cachorros (raças populares no Brasil) ────────────────────────────────────
  {
    name: 'SRD (Vira-lata)',
    species: 'Cachorro',
    origin: 'Brasil',
    size: 'Médio',
    lifespan: '13–18 anos',
    temperament: ['Resiliente', 'Adaptável', 'Leal', 'Inteligente'],
    characteristics: 'Mistura de raças, pelagem e porte variados. Extremamente resistente geneticamente.',
    care: ['Vacinação em dia', 'Vermifugação regular', 'Exercício diário', 'Alimentação equilibrada'],
    curiosity: 'Estudos mostram que vira-latas têm maior expectativa de vida e menos doenças hereditárias que raças puras.',
    emoji: '🐕',
  },
  {
    name: 'Pitbull (APBT)',
    species: 'Cachorro',
    origin: 'EUA',
    size: 'Médio',
    lifespan: '12–16 anos',
    temperament: ['Leal', 'Corajoso', 'Afetuoso', 'Energético'],
    characteristics: 'Corpo musculoso e compacto, cabeça larga, pelo curto. Extremamente forte para o seu tamanho.',
    care: ['Socialização desde filhote', 'Exercício diário intenso', 'Treinamento positivo', 'Escovação semanal'],
    curiosity: 'Apesar da reputação, o APBT foi historicamente chamado de "babá dog" por ser gentil com crianças.',
    emoji: '🐕',
  },
  {
    name: 'Akita',
    species: 'Cachorro',
    origin: 'Japão',
    size: 'Grande',
    lifespan: '10–13 anos',
    temperament: ['Leal', 'Digno', 'Corajoso', 'Reservado'],
    characteristics: 'Corpo robusto, cauda enrolada, pelagem densa dupla, expressão nobre e serena.',
    care: ['Socialização precoce', 'Exercício diário moderado', 'Escovação intensa na muda', 'Treinamento firme e consistente'],
    curiosity: 'Hachiko, o akita mais famoso do mundo, esperou seu dono na estação de trem por 9 anos após sua morte.',
    emoji: '🐕',
  },
  {
    name: 'Cocker Spaniel',
    species: 'Cachorro',
    origin: 'Inglaterra',
    size: 'Médio',
    lifespan: '12–15 anos',
    temperament: ['Alegre', 'Afetuoso', 'Dócil', 'Ativo'],
    characteristics: 'Orelhas longas e sedosas, olhos expressivos e amendoados, pelo ondulado e abundante.',
    care: ['Escovação diária', 'Limpeza das orelhas semanal', 'Banhos regulares', 'Exercício moderado diário'],
    curiosity: 'É a raça que inspirou a famosa cena do espaguete no filme "A Dama e o Vagabundo" da Disney.',
    emoji: '🐕',
  },
  {
    name: 'Chow Chow',
    species: 'Cachorro',
    origin: 'China',
    size: 'Grande',
    lifespan: '9–15 anos',
    temperament: ['Independente', 'Leal', 'Reservado', 'Protetor'],
    characteristics: 'Língua azul-escura única, juba ao redor da cabeça, pelagem densa. Andar característico.',
    care: ['Escovação frequente', 'Evitar calor excessivo', 'Socialização precoce', 'Exercício moderado'],
    curiosity: 'São uma das raças mais antigas do mundo — registros de 2.000 anos na China como cão de guarda imperial.',
    emoji: '🦁',
  },
  {
    name: 'Dobermann',
    species: 'Cachorro',
    origin: 'Alemanha',
    size: 'Grande',
    lifespan: '10–13 anos',
    temperament: ['Inteligente', 'Alerta', 'Leal', 'Energético'],
    characteristics: 'Corpo elegante e musculoso, pelo curto e brilhante, postura atlética e imponente.',
    care: ['Exercício diário intenso', 'Estimulação mental', 'Treinamento profissional', 'Monitorar coração — propenso à cardiomiopatia'],
    curiosity: 'Foi criado por Louis Dobermann, cobrador de impostos alemão que queria proteção em suas rondas.',
    emoji: '🐕',
  },
  {
    name: 'São Bernardo',
    species: 'Cachorro',
    origin: 'Suíça',
    size: 'Gigante',
    lifespan: '8–10 anos',
    temperament: ['Gentil', 'Paciente', 'Amigável', 'Calmo'],
    characteristics: 'Porte gigantesco, pelagem densa, cabeça larga e expressão bondosa. Baba bastante.',
    care: ['Espaço amplo', 'Exercício moderado', 'Escovação frequente', 'Monitorar articulações e peso'],
    curiosity: 'Os famosos barris de conhaque que esses cães supostamente carregavam nunca foram reais — são lenda.',
    emoji: '🐕',
  },
  {
    name: 'Shar Pei',
    species: 'Cachorro',
    origin: 'China',
    size: 'Médio',
    lifespan: '8–12 anos',
    temperament: ['Calmo', 'Leal', 'Independente', 'Protetor'],
    characteristics: 'Inconfundíveis pregas de pele por todo o corpo, focinho de hipopótamo, pelo curto e áspero.',
    care: ['Limpeza das pregas diária', 'Monitorar olhos — propenso ao entrópio', 'Exercício moderado', 'Veterinário regular'],
    curiosity: 'Quase extinto na China comunista — sobreviveu graças a criadores de Hong Kong nos anos 1970.',
    emoji: '🐕',
  },

  // ── Gatos (raças populares no Brasil) ───────────────────────────────────────
  {
    name: 'SRD - Gato de Rua',
    species: 'Gato',
    origin: 'Brasil',
    size: 'Médio',
    lifespan: '12–20 anos',
    temperament: ['Independente', 'Adaptável', 'Resiliente', 'Curioso'],
    characteristics: 'Mistura de raças, pelagem e cores variadas. Geneticamente mais resistente que raças puras.',
    care: ['Vacinação e vermifugação', 'Castração', 'Enriquecimento ambiental', 'Alimentação de qualidade'],
    curiosity: 'Gatos SRD castrados e vacinados vivem em média mais que gatos de raça pura.',
    emoji: '🐱',
  },
  {
    name: 'Angorá Turco',
    species: 'Gato',
    origin: 'Turquia',
    size: 'Médio',
    lifespan: '12–18 anos',
    temperament: ['Ativo', 'Inteligente', 'Afetuoso', 'Curioso'],
    characteristics: 'Pelo longo e sedoso sem subpelo, corpo esguio e elegante, olhos amendoados.',
    care: ['Escovação semanal', 'Brinquedos interativos', 'Companhia frequente', 'Evitar isolamento'],
    curiosity: 'É uma das raças mais antigas da Europa — chegou do Oriente Médio no século XVII.',
    emoji: '🐱',
  },
  {
    name: 'Pelo Curto Brasileiro',
    species: 'Gato',
    origin: 'Brasil',
    size: 'Médio',
    lifespan: '14–20 anos',
    temperament: ['Ativo', 'Sociável', 'Independente', 'Adaptável'],
    characteristics: 'Pelo curto e liso, corpo ágil e musculoso. Grande variedade de cores e padrões.',
    care: ['Escovação quinzenal', 'Castração recomendada', 'Brinquedos e arranhadores', 'Alimentação balanceada'],
    curiosity: 'É a raça brasileira reconhecida pela ABGA — descendente dos gatos trazidos pelos portugueses no século XVI.',
    emoji: '🐱',
  },

  // ── Cobaia (Porquinho-da-índia) ──────────────────────────────────────────────
  { name: 'Americano (Short Hair)', species: 'Cobaia', origin: 'América do Sul', size: 'Pequeno', lifespan: '4–8 anos', temperament: ['Dócil', 'Sociável', 'Curioso'], characteristics: 'Pelo curto e liso, corpo robusto, sem cauda. A raça mais comum como pet.', care: ['Viveiro espaçoso', 'Companhia de outro cobaia', 'Feno à vontade', 'Vitamina C diária'], curiosity: 'Apesar do nome, não são da Índia — são originários dos Andes sul-americanos.', emoji: '🐹' },
  { name: 'Abissínio', species: 'Cobaia', origin: 'América do Sul', size: 'Pequeno', lifespan: '4–8 anos', temperament: ['Brincalhão', 'Ativo', 'Vocal'], characteristics: 'Pelo com redemoinhos (rosetas) em todo o corpo. Aparência sempre "bagunçada".', care: ['Escovação semanal', 'Espaço para correr', 'Vitamina C diária', 'Companhia essencial'], curiosity: 'Os redemoinhos do pelo são chamados de rosetas — cada cobaia tem um padrão único.', emoji: '🐹' },
  { name: 'Peruano', species: 'Cobaia', origin: 'Peru', size: 'Pequeno', lifespan: '4–8 anos', temperament: ['Calmo', 'Dócil', 'Afetuoso'], characteristics: 'Pelo longo (até 50cm) que cobre todo o corpo. Parece um tapete ambulante.', care: ['Escovação diária obrigatória', 'Tosa regular', 'Vitamina C', 'Espaço limpo e seco'], curiosity: 'Seu pelo pode crescer continuamente — sem cuidados adequados, chega a arrastar no chão.', emoji: '🐹' },
  { name: 'Teddy', species: 'Cobaia', origin: 'EUA', size: 'Pequeno', lifespan: '4–8 anos', temperament: ['Dócil', 'Tranquilo', 'Sociável'], characteristics: 'Pelo curto, denso e crespo — textura aveludada. Nariz arrebitado característico.', care: ['Escovação semanal', 'Limpeza das orelhas', 'Vitamina C diária', 'Companhia essencial'], curiosity: 'Seu pelo "crespo" é resultado de uma mutação genética surgida espontaneamente.', emoji: '🐹' },

  // ── Chinchila ────────────────────────────────────────────────────────────────
  { name: 'Chinchila Padrão (Cinza)', species: 'Chinchila', origin: 'Chile / Andes', size: 'Pequeno', lifespan: '10–20 anos', temperament: ['Ativo', 'Curioso', 'Tímido', 'Noturno'], characteristics: 'Pelo cinza-azulado extremamente denso e macio. Orelhas grandes e arredondadas.', care: ['Banho de areia especial (não água)', 'Temperatura abaixo de 25°C', 'Gaiola alta para pular', 'Feno de qualidade'], curiosity: 'Têm o pelo mais denso entre os mamíferos terrestres — 60 a 80 fios por folículo.', emoji: '🐭' },
  { name: 'Chinchila Beige', species: 'Chinchila', origin: 'Criação seletiva', size: 'Pequeno', lifespan: '10–20 anos', temperament: ['Ativo', 'Sociável', 'Curioso'], characteristics: 'Coloração bege-creme resultado de mutação genética. Olhos vermelhos ou negros.', care: ['Banho de areia', 'Ambiente fresco e seco', 'Dieta à base de feno', 'Companhia de outra chinchila'], curiosity: 'A mutação beige surgiu em cativeiro nos anos 1950 — não existe na natureza.', emoji: '🐭' },
  { name: 'Chinchila Branca (White)', species: 'Chinchila', origin: 'Criação seletiva', size: 'Pequeno', lifespan: '10–18 anos', temperament: ['Dócil', 'Curioso', 'Ativo'], characteristics: 'Pelagem branca pura. Pode ter manchas escuras (mosaic) ou ser completamente branca.', care: ['Banho de areia', 'Temperatura controlada', 'Feno ilimitado', 'Evitar umidade'], curiosity: 'Chinchilas brancas homozigóticas (white-white) não sobrevivem — a combinação é letal no embrião.', emoji: '🐭' },

  // ── Furão ────────────────────────────────────────────────────────────────────
  { name: 'Furão Doméstico', species: 'Furão', origin: 'Europa', size: 'Pequeno', lifespan: '6–10 anos', temperament: ['Brincalhão', 'Curioso', 'Ativo', 'Sociável'], characteristics: 'Corpo alongado e flexível, focinho pontudo, pelo variado. Dorme até 18h por dia.', care: ['Gaiola grande com andares', 'Solto por ao menos 4h/dia', 'Vacinação obrigatória', 'Castração recomendada'], curiosity: 'São domesticados há mais de 2.500 anos — usados para caçar coelhos em tocas na Europa medieval.', emoji: '🦦' },
  { name: 'Furão Albino', species: 'Furão', origin: 'Europa', size: 'Pequeno', lifespan: '6–10 anos', temperament: ['Dócil', 'Brincalhão', 'Curioso'], characteristics: 'Pelagem branca ou creme, olhos vermelhos ou rosados. Resultado de ausência de pigmentação.', care: ['Proteção da luz solar forte', 'Vacinação', 'Castração', 'Brinquedos e interação diária'], curiosity: 'Furões albinos têm maior risco de surdez congênita associada à falta de pigmentação.', emoji: '🦦' },
  { name: 'Furão Sable', species: 'Furão', origin: 'Europa', size: 'Pequeno', lifespan: '6–10 anos', temperament: ['Energético', 'Brincalhão', 'Social'], characteristics: 'Coloração mais comum — marrom escuro (sable) com máscara e patas mais escuras.', care: ['Interação diária obrigatória', 'Gaiola segura', 'Veterinário com experiência em furões', 'Dieta proteica'], curiosity: 'O cheiro característico dos furões vem de glândulas sebáceas — a castração reduz significativamente o odor.', emoji: '🦦' },
];

/** Retorna raças filtradas por espécie para autocomplete. */
export function getBreedsBySpecies(species: string): string[] {
  return BREEDS
    .filter(b => b.species === species)
    .map(b => b.name);
}

/** Busca informações da raça pelo nome (case-insensitive, normalizado). */
export function findBreedInfo(breedName: string, species?: string): BreedInfo | null {
  if (!breedName?.trim()) return null;
  const normalized = breedName.trim().toLowerCase();
  return (
    BREEDS.find(b => {
      const nameMatch = b.name.toLowerCase() === normalized ||
        b.name.toLowerCase().includes(normalized) ||
        normalized.includes(b.name.toLowerCase());
      const speciesMatch = !species || b.species === species;
      return nameMatch && speciesMatch;
    }) ?? null
  );
}

export { BREEDS };
